#
# Table structure for table 'users'
#

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `userID` INTEGER NOT NULL AUTO_INCREMENT, 
  `email` VARCHAR(50), 
  `sharedAccount` TINYINT(1) DEFAULT 0, 
  `password` VARCHAR(50) NOT NULL, 
  `lastLogin` DATETIME, 
  `personID` INTEGER DEFAULT 0, 
  `createDate` DATETIME, 
  `lastPestered` DATETIME, 
  `KeemAccess` TINYINT(1) DEFAULT 0, 
  `HusbandAccess` TINYINT(1) DEFAULT 0, 
  `KemlerAccess` TINYINT(1) DEFAULT 0, 
  `KaplanAccess` TINYINT(1) DEFAULT 0, 
  `Logins` INTEGER DEFAULT 0, 
  `ActiveBool` TINYINT(1) DEFAULT 0, 
  `connection_notes` VARCHAR(255), 
  `superAdmin` TINYINT(1) DEFAULT 0, 
  `furthestHTML` VARCHAR(255), 
  INDEX (`personID`), 
  PRIMARY KEY (`userID`), 
  INDEX (`userID`)
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;

#
# Dumping data for table 'users'
#

INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (6, 'rhusband@saintclares.org', 0, 'bobhpsw1', '2014-05-08 14:43:43', 80, NULL, '2010-10-25 00:00:00', 1, 1, 0, 0, 13, 1, '', 0, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (7, 'ekdolph@comcast.net', 0, 'password', '2010-07-08 22:35:06', 37, NULL, '2010-11-13 00:00:00', 0, 0, 1, 1, 2, 1, '', 0, '<a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>,<a href=\"/family/family.asp?familyid=4\">Sol & Ida Kemler</a>,<a href=\"/family/family.asp?familyid=90\">Aaron & Rochel Kobrin</a>,<a href=\"/family/family.asp?familyid=119\">Max & Toba Shapiro</');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (8, 'bartlett.d@husky.neu.edu', 0, 'password', '2010-10-26 09:17:07', 83, NULL, '2010-10-25 00:00:00', 1, 1, 0, 0, 1, 1, '', 0, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (9, 'ladolph@comcast.net', 0, 'password', NULL, 40, NULL, NULL, 0, 0, 1, 1, 0, 1, NULL, 0, '<a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>,<a href=\"/family/family.asp?familyid=4\">Sol & Ida Kemler</a>,<a href=\"/family/family.asp?familyid=90\">Aaron & Rochel Kobrin</a>,<a href=\"/family/family.asp?familyid=119\">Max & Toba Shapiro</');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (10, 'aok@aya.yale.edu', 0, 'password', '2010-06-27 18:10:21', 108, NULL, '2010-06-27 00:00:00', 0, 0, 1, 0, 1, 1, '', 0, 'Paternal side: 2 sets of great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (11, 'b.svikhart@comcast.net', 0, 'password', NULL, 109, NULL, NULL, 0, 0, 1, 0, 0, 1, NULL, 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (12, 'bethkemler@aol.com', 0, 'password', '2010-07-13 21:52:22', 106, NULL, '2010-11-13 00:00:00', 0, 0, 1, 0, 2, 1, '', 0, 'Paternal side: 2 sets of great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (13, 'jlazkem@aol.com', 0, 'password', NULL, 118, NULL, NULL, 0, 0, 1, 0, 0, 1, NULL, 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (14, 'eleanorfeinberg@sbcglobal.net', 0, 'password', NULL, 114, NULL, '2010-11-13 00:00:00', 0, 0, 1, 0, 0, 1, NULL, 0, 'Paternal side: 2 sets of great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (15, 'wfeinber@uiuc.edu', 0, 'password', NULL, 116, NULL, NULL, 0, 0, 1, 0, 0, 1, NULL, 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (16, 'rachel_weeks04@yahoo.com', 0, 'berger01', '2010-03-21 20:30:00', 133, NULL, '2010-03-16 00:00:00', 0, 0, 1, 0, 3, 1, '', 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (17, 'dberger@wellesley.edu', 0, 'password', NULL, 112, NULL, NULL, 0, 0, 1, 0, 0, 1, NULL, 0, 'Maternal fathers side: 2 sets of great great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (18, 'dbnitkin66@hotmail.com', 0, 'password', '2010-03-20 08:52:44', 420, NULL, '2010-09-14 00:00:00', 0, 0, 1, 0, 1, 1, 'David and dad are second cousins: David came from Etta Nitkin via Sonny. ', 0, 'Paternal Mothers side: great grandparents <a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/>Paternal fathers side: great grandparents <a href=\"/family/family.asp?familyid=123\">Nathaniel & Lena Nitkin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (19, 'kj.kobrin.cohen@gmail.com', 0, 'sunspot', '2010-08-23 22:04:14', 99, NULL, '2010-08-20 00:00:00', 0, 0, 0, 1, 4, 1, 'Kal was cousins with dad (his dad was Joe), Karen is his daughter and second cousins with me', 0, 'Great great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (20, 'joseph@kobrin.co.uk', 0, 'password', NULL, 464, NULL, '2010-07-06 00:00:00', 0, 0, 0, 1, 0, 1, NULL, 0, 'Great great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (21, 'sharon@kobrin.co.uk', 0, 'norahs', '2011-02-11 03:10:03', 463, NULL, '2010-08-18 00:00:00', 0, 0, 0, 1, 4, 1, 'Sharon married Dave Kobrin.  Dave and dad are second cousins: Dave came from Solomon via Joe, and dad came from his brother Kalman via Larry. ', 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (22, 'PRECHER@aol.com', 0, 'Natick68', '2014-02-09 18:14:57', 188, NULL, '2010-08-21 00:00:00', 0, 0, 0, 1, 5, 1, 'Barry Kloper my second cousin: the son of Mildred, the daughter of Joe Kaplan, who was the brother of Abraham ', 0, 'Great great great grandparents (mothers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (23, 'EVEandRAY@aol.com', 0, 'password', '2010-07-17 21:08:27', 342, NULL, '2010-08-26 00:00:00', 0, 0, 0, 1, 5, 1, 'Evelyn and dad are second cousins: Evelyn came from Nathan via Noah, and dad came from his brother Kalman via Larry. ', 0, 'Great great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (24, 'tgoldberg@carolina.rr.com', 1, 'cessnagold', '2010-06-20 21:00:49', 344, NULL, '2010-09-14 00:00:00', 0, 0, 0, 1, 2, 1, 'Linda and dad are second cousins: Linda came from Nathan via Noah, and dad came from his brother Kalman via Larry.', 0, 'Great great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (25, 'ansuincg@buffalostate.edu', 0, 'password', NULL, 70, NULL, '2010-10-25 00:00:00', 1, 0, 0, 0, 0, 1, NULL, 0, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (26, 'scudieroan@Dare.k12.nc.us', 0, 'password', NULL, 72, NULL, '2010-10-25 00:00:00', 1, 0, 0, 0, 0, 1, NULL, 0, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (27, 'tjk@kih.net', 0, 'MariA1946K', '2010-05-09 14:41:29', 69, NULL, '2010-10-25 00:00:00', 1, 0, 0, 0, 2, 1, '', 0, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (28, 'khusband@realtyusa.com', 0, 'password', NULL, 182, NULL, NULL, 0, 1, 0, 0, 0, 1, NULL, 0, 'Great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=172\">Thomas & Elanor Husband</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (30, 'eghart@msn.com', 0, 'joannbarbara', '2009-11-30 22:13:38', 452, NULL, '2010-03-16 00:00:00', 0, 0, 1, 0, 2, 1, '', 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (31, 'MUnger@rubinrudman.com', 0, 'password', NULL, 296, NULL, '2010-10-25 00:00:00', 1, 1, 0, 0, 0, 1, NULL, 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (32, 'acdolph@comcast.net', 0, 'password', NULL, 39, NULL, NULL, 0, 0, 1, 1, 0, 1, NULL, 0, '<a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>,<a href=\"/family/family.asp?familyid=4\">Sol & Ida Kemler</a>,<a href=\"/family/family.asp?familyid=90\">Aaron & Rochel Kobrin</a>,<a href=\"/family/family.asp?familyid=119\">Max & Toba Shapiro</');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (33, 'marissakemler@hotmail.com', 0, 'password', '2009-11-30 17:10:06', 120, NULL, '2010-06-19 00:00:00', 0, 0, 1, 0, 1, 1, '', 0, 'Paternal fathers side: 2 sets of great great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (34, 'rschultz44@aol.com', 0, 'password', '2010-02-04 13:27:00', 96, '2010-01-24 00:00:00', '2010-08-20 00:00:00', 0, 0, 0, 1, 2, 1, 'Rosealyn is my second cousin once removed, coming from Jeff Schultz (my second cousin), Dorothy Schultz (cousins with dad), and Joe Kaplan. ', 0, 'Great great great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (35, 'dianekaplan@gmail.com', 1, 'password1', '2011-02-11 03:06:21', 24, '2010-01-24 00:00:00', NULL, 0, 0, 1, 0, 33, 1, NULL, 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (36, 'vancemyrna@yahoo.com', 0, 'bernie2', '2011-09-09 19:40:08', 597, '2010-01-31 00:00:00', '2010-08-24 00:00:00', 1, 0, 0, 0, 10, 1, 'Myrna would have been third cousins with grandma: she came from Arlie, Edward, and Julius Pochel, and Julius was the sister of Emily, who had Helen/Adele/grandma', 0, 'Great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=107\">Edward & Catherine Pochel</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (37, 'deborah7@charter.net', 0, 'password', '2010-03-27 18:38:03', 125, '2010-03-21 00:00:00', '2010-05-07 00:00:00', 0, 0, 1, 0, 3, 1, 'Debbie is the daughter of Eleanor & Wally', 0, 'Mothers fathers side: 2 sets of great great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (86, 'kkatelan@yahoo.com', 0, '$2y4fun', '2012-02-24 23:30:22', 627, '2012-01-12 18:26:54', NULL, 0, 0, 1, 0, 6, 1, 'granddaughter of Stanley', 0, 'Great great grandparents (father\'\'s father\'\'s side): <br/><a href=/family/family.asp?familyid=3>Ida & Solomon Kemler</a> and <a href=/family/family.asp?familyid=3>Fanny & Barnett Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (1, 'ok4mee@hotmail.com', 0, 'ilike2go', '2015-01-04 18:47:15', 86, NULL, '2010-10-25 00:00:00', 1, 1, 1, 1, 417, 1, '', 1, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>\t ');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (2, 'lkaplan000@gmail.com', 0, 'David', '2014-05-10 17:08:18', 85, NULL, '2010-10-25 00:00:00', 1, 1, 1, 1, 10, 1, '', 1, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (3, 'kaplanfin@aol.com', 0, 'password', '2011-08-16 13:59:13', 81, NULL, '2010-10-25 00:00:00', 1, 1, 1, 1, 16, 1, '', 1, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (4, 'kenkaplan@aol.com', 0, 'password', '2013-08-30 21:56:03', 36, NULL, '2010-11-13 00:00:00', 1, 1, 1, 1, 14, 1, NULL, 0, '<a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>,<a href=\"/family/family.asp?familyid=4\">Sol & Ida Kemler</a>,<a href=\"/family/family.asp?familyid=90\">Aaron & Rochel Kobrin</a>,<a href=\"/family/family.asp?familyid=119\">Max & Toba Shapiro</');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (5, 'bartlett.family@comcast.net', 0, 'password', '2010-07-05 20:05:51', 79, NULL, '2010-10-25 00:00:00', 1, 1, 0, 0, 5, 1, '', 0, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (38, 'judyforeman@myhealthsense.com', 0, 'password', '2010-05-07 22:03:39', 648, '2010-05-06 00:00:00', '2010-07-06 00:00:00', 0, 0, 1, 1, 1, 1, '', 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (39, 'annmelman@gmail.com', 0, 'password', '2008-08-18 20:33:44', 651, '2010-05-08 00:00:00', '2010-08-15 00:00:00', 0, 0, 0, 1, 0, 1, 'Wife of Dennis Melman, who came from Solomon Kobrin, the brother of Kal', 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (40, 'damech@aol.com', 0, 'password', NULL, 548, '2010-05-11 00:00:00', '2010-07-06 00:00:00', 0, 0, 0, 1, 0, 1, 'Daughter of Evelyn: her great-grandfather (Nathan Kobrin) was brothers with mine, Kalman Kaplan ', 0, 'Great great great grandparents (mothers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (41, 'thezorns@gmail.com', 1, 'ppj462', '2010-08-23 13:47:53', 6, '2010-05-12 00:00:00', '2010-08-21 00:00:00', 0, 0, 1, 0, 5, 1, '', 0, 'Great grandparents (mothers mothers side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (42, 'jbzorn1@comcast.net', 0, 'JZpassword', NULL, 8, '2010-05-12 00:00:00', '2010-08-21 00:00:00', 0, 0, 1, 0, 0, 1, '', 0, 'Great grandparents (mothers mothers side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (43, 'pamalman@msn.com', 0, 'saltsk8', '2010-07-07 09:58:19', 655, '2010-06-02 00:00:00', '2010-08-21 00:00:00', 0, 0, 0, 1, 2, 1, 'widow of Eric Alman, who was the grandson of Sarah Alman. Sarah was the sister of Larry/Abraham', 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (45, 'dianekaplan@gmail.com', 1, 'password1', '2010-06-15 23:50:22', 105, '2010-06-12 00:00:00', NULL, 0, 0, 1, 0, 2, 1, NULL, 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (46, 'tgoldberg@carolina.rr.com', 1, 'cessnagold', NULL, 498, '2010-06-15 00:00:00', '2010-07-06 00:00:00', 0, 0, 0, 1, 0, 1, 'Linda and dad are second cousins: Linda came from Nathan via Noah, and dad came from his brother Kalman via Larry.', 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (47, 'smkelk@earthlink.net', 1, 'password', NULL, 117, '2010-06-15 00:00:00', NULL, 0, 0, 1, 0, 0, 1, NULL, 0, NULL);
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (48, 'Kittyfelone@Gmail.com', 0, 'dragon', '2011-01-01 20:32:04', 573, '2010-06-19 00:00:00', '2010-08-21 00:00:00', 0, 0, 0, 1, 4, 1, 'daughter of Barry Kloper, son of Mildred, cousin of dad', 0, 'Great great great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (49, 'JudiKO@AOL.COM', 0, 'JKpassword', NULL, 189, '2010-06-19 00:00:00', '2010-08-21 00:00:00', 0, 0, 0, 1, 0, 1, 'Mildred was the cousin of dad, and Judi is her daughter (sister of Barry Kloper)', 0, 'Great great great grandparents (mothers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (50, 'hon600rr@yahoo.com', 0, 'password', '2010-06-20 16:31:38', 572, '2010-06-20 00:00:00', '2010-08-21 00:00:00', 0, 0, 0, 1, 1, 1, 'Wendy is the daughter of Barry Kloper', 0, 'Great great great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (51, 'andreaobrien1@hotmail.com', 0, 'password', '2011-03-23 20:30:20', 89, '2010-06-23 00:00:00', '2010-07-06 00:00:00', 0, 0, 0, 1, 8, 1, 'Andrea is the daughter of Kal, cousin of dad', 0, 'Great great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (54, 'Sportsfan5390@aol.com', 0, 'bruschi', '2010-11-26 16:21:46', 674, '2010-07-05 00:00:00', '2010-08-18 00:00:00', 0, 0, 0, 1, 9, 1, 'Jacob came from Sarah Alman, Harvey, Steven', 0, 'Great great great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (56, 'jnatkin@mindspring.com', 0, 'password', '2010-07-07 21:03:29', 712, '2010-07-07 00:00:00', '2010-08-18 00:00:00', 0, 0, 0, 1, 1, 1, 'Aaron/Yetta/Dora', 0, 'Great great great grandparents (mothers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (71, 'ansuini.c@law.wlu.edu', 0, 'password', NULL, 218, '2010-07-21 00:05:00', '2010-10-25 00:00:00', 1, 0, 0, 0, 0, 1, 'Cathys daughter', 0, '5 sets of great great great great great great great great grandparents (mother\'\'s mother\'\'s side): <br/>see hot pink families <a href=/family/history.asp?displaybranch=y>here</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (76, 'harveyflamingo@att.net', 0, 'tennis11', '2010-08-20 09:36:31', 161, '2010-08-18 13:28:31', '2010-08-19 00:00:00', 0, 0, 0, 1, 1, 1, 'Son of Sarah Kaplan', 0, ' Great great grandparents (mothers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (77, 'petezorn@comcast.net', 0, 'password', NULL, 166, '2010-08-22 23:02:20', '2010-08-22 00:00:00', 0, 0, 1, 0, 0, 1, 'Child of Stu & Elaine', 0, ' Great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (52, 'bsneag@ibi.co.za', 0, 'password', '2010-07-13 08:37:04', 680, '2010-07-02 00:00:00', '2010-08-20 00:00:00', 0, 0, 0, 1, 10, 1, 'Brian is dads second cousin, he came down through Beila', 0, 'Great great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (53, 'mfitt@global.co.za', 0, 'password', '2010-07-08 14:25:27', 682, '2010-07-02 00:00:00', '2010-08-20 00:00:00', 0, 0, 0, 1, 2, 1, 'Doreen is dads second cousin, he came down through Beila', 0, 'Great great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (57, 'martinslon@verizon.net', 0, 'password', '2010-07-12 22:40:28', 715, '2010-07-07 00:00:00', '2010-09-21 00:00:00', 0, 0, 0, 1, 1, 1, 'Aaron/Annie/Hymie/Martin', 0, 'Great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (58, 'barry.slon@gmail.com', 0, 'password', NULL, 716, '2010-07-07 00:00:00', NULL, 0, 0, 0, 1, 0, 1, 'Aaron/Annie/Hymie/Barry', 0, 'Great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (59, 'editordan2002@yahoo.com', 0, 'password', NULL, 717, '2010-07-07 00:00:00', NULL, 0, 0, 0, 1, 0, 1, 'Aaron/Annie/Abe/Daniella', 0, 'Great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (78, 'ZornAdams.Pamela@tatravelcenters.com', 0, 'password', '2010-08-22 23:24:37', 167, '2010-08-22 23:02:58', '2010-08-22 00:00:00', 0, 0, 1, 0, 1, 1, 'Child of Stu & Elaine', 0, ' Great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (79, 'jeremy.zorn@gmail.com', 0, 'password', '2010-08-22 23:34:46', 168, '2010-08-22 23:03:16', '2010-08-22 00:00:00', 0, 0, 1, 0, 1, 1, 'Child of Stu & Elaine', 0, ' Great great grandparents (fathers mothers side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (80, 'thezorns@gmail.com', 1, 'ppj462', NULL, 7, '2010-08-22 23:13:20', '2010-08-22 00:00:00', 0, 0, 1, 0, 0, 1, '', 0, '');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (68, 'gsneag@pacbell.net', 0, 'garden01', '2010-07-14 12:04:17', 741, '2010-07-14 08:44:08', '2010-08-23 00:00:00', 0, 0, 0, 1, 1, 1, 'Gary/Maurice/Beila Kobrin', 0, ' Great great grandparents (father\'\'s mother\'\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (81, 'denvic35@orange.fr', 0, 'DKpassword', NULL, 347, '2010-09-19 09:54:09', '2010-09-19 00:00:00', 0, 0, 0, 1, 0, 1, 'Nathan/Sam/Dennis', 0, ' Great great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (82, 'berthas@bigpond.com', 0, 'BSpassword', NULL, 714, '2010-09-21 08:02:02', '2010-09-21 00:00:00', 0, 0, 0, 1, 0, 1, 'Bertha married Hymie, son of Kalman\'\'s sister Annie', 0, '');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (83, 'dscohen00@gmail.com', 0, 'DCpassword', '2013-12-31 06:36:28', 836, '2010-11-21 16:32:45', NULL, 0, 0, 1, 0, 4, 1, 'Grandson of Rose Kemler', 0, ' Great grandparents (father\'\'s mother\'\'s side): <br/><a href=/family/family.asp?familyid=4>Solomon & Ida Kemler</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (84, 'stanchait12@gmail.com', 0, 'NKpassword', NULL, 350, '2011-05-19 07:17:29', NULL, 0, 0, 0, 1, 0, 1, 'Neville comes from Nathan Kobrin via Toly ', 0, ' Great great grandparents (father\'\'s father\'\'s side): <br/><a href=/family/family.asp?familyid=194>Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (85, 'CarenA4GT@aol.com', 0, 'CApassword', '2011-09-11 19:20:07', 183, '2011-07-21 15:55:42', NULL, 0, 1, 0, 0, 3, 1, 'moms cousin', 0, ' Great great grandparents (fathers fathers side): <br/><a href=/family/family.asp?familyid=172>Thomas & Elanor Husband</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (87, 'allan_marcus@student.uml.edu', 0, 'AMpassword', NULL, 857, '2012-01-17 21:59:40', NULL, 0, 0, 0, 1, 0, 1, 'Great-grandson of Sarah Alman', 0, ' Great great great great great grandparents (father\'\'s father\'\'s side): <br/><a href=/family/family.asp?familyid=194>Joseph & Sarah Kobrin</a>');
INSERT INTO `users` (`userID`, `email`, `sharedAccount`, `password`, `lastLogin`, `personID`, `createDate`, `lastPestered`, `KeemAccess`, `HusbandAccess`, `KemlerAccess`, `KaplanAccess`, `Logins`, `ActiveBool`, `connection_notes`, `superAdmin`, `furthestHTML`) VALUES (103, 'redsrc@aol.com', 0, 'SSpassword', NULL, 288, '2014-05-05 19:39:22', NULL, 0, 0, 0, 1, 0, 1, 'Stephanie was the wife of Arnie, whose mother Dorothy was the first cousin of Abraham Larry Kaplan', 0, 'Married into the family- spouse was: <br/><a href=/family/person.asp?personID=196>Arnie Schultz</a>');
# 71 records

