# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Families',
            fields=[
                ('familyid', models.IntegerField(serialize=False, primary_key=True, db_column='familyID')),
                ('caption', models.CharField(max_length=50, blank=True)),
                ('motherid', models.IntegerField(null=True, db_column='motherID', blank=True)),
                ('fatherid', models.IntegerField(null=True, db_column='fatherID', blank=True)),
                ('divorced', models.IntegerField(null=True, blank=True)),
                ('marriagedate', models.CharField(max_length=50, db_column='marriageDate', blank=True)),
                ('notes1', models.CharField(max_length=255, db_column='Notes1', blank=True)),
                ('notes2', models.CharField(max_length=255, db_column='Notes2', blank=True)),
                ('originalbool', models.IntegerField(null=True, db_column='originalBool', blank=True)),
                ('nokidsbool', models.IntegerField(null=True, db_column='noKidsBool', blank=True)),
                ('sequence', models.IntegerField(null=True, blank=True)),
                ('branch', models.IntegerField(null=True, db_column='Branch', blank=True)),
                ('branchseq', models.CharField(max_length=5, db_column='Branchseq', blank=True)),
                ('keembool', models.IntegerField(null=True, db_column='KeemBool', blank=True)),
                ('husbandbool', models.IntegerField(null=True, db_column='HusbandBool', blank=True)),
                ('kemlerbool', models.IntegerField(null=True, db_column='KemlerBool', blank=True)),
                ('kaplanbool', models.IntegerField(null=True, db_column='KaplanBool', blank=True)),
                ('showonbranchviewbool', models.IntegerField(null=True, db_column='showOnBranchViewBool', blank=True)),
                ('flag1', models.CharField(max_length=255, blank=True)),
                ('flag2', models.CharField(max_length=255, blank=True)),
                ('lastmodified', models.DateTimeField(null=True, db_column='lastModified', blank=True)),
            ],
            options={
                'db_table': 'families',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Imageperson',
            fields=[
                ('imagegroupid', models.IntegerField(serialize=False, primary_key=True, db_column='imageGroupID')),
                ('imageid', models.IntegerField(null=True, db_column='imageID', blank=True)),
                ('personid', models.IntegerField(null=True, db_column='personID', blank=True)),
            ],
            options={
                'db_table': 'imagePerson',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('imageid', models.IntegerField(serialize=False, primary_key=True, db_column='imageID')),
                ('bigname', models.CharField(max_length=50, db_column='bigName', blank=True)),
                ('stdname', models.CharField(max_length=50, db_column='stdName', blank=True)),
                ('littlename', models.CharField(max_length=50, db_column='littleName', blank=True)),
                ('caption', models.CharField(max_length=50, blank=True)),
                ('subject', models.IntegerField(null=True, blank=True)),
                ('featurebool', models.IntegerField(null=True, db_column='featureBool', blank=True)),
                ('year', models.CharField(max_length=25, db_column='Year', blank=True)),
                ('family', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteid', models.IntegerField(serialize=False, primary_key=True, db_column='noteID')),
                ('refid', models.IntegerField(null=True, db_column='refID', blank=True)),
                ('type', models.IntegerField(null=True, db_column='Type', blank=True)),
                ('fromperson', models.IntegerField(null=True, db_column='fromPerson', blank=True)),
                ('body', models.TextField(blank=True)),
                ('fromname', models.CharField(max_length=50, db_column='fromName', blank=True)),
                ('date', models.DateTimeField(null=True, blank=True)),
                ('activebool', models.IntegerField(null=True, db_column='ActiveBool', blank=True)),
            ],
            options={
                'db_table': 'Notes',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('personid', models.IntegerField(serialize=False, primary_key=True, db_column='personID')),
                ('first', models.CharField(max_length=15, blank=True)),
                ('middle', models.CharField(max_length=15, blank=True)),
                ('last', models.CharField(max_length=15, blank=True)),
                ('maiden', models.CharField(max_length=15, blank=True)),
                ('nickname', models.CharField(max_length=15, blank=True)),
                ('face', models.CharField(max_length=50, blank=True)),
                ('siblingseq', models.IntegerField(null=True, db_column='siblingSeq', blank=True)),
                ('keembool', models.IntegerField(null=True, db_column='KeemBool', blank=True)),
                ('husbandbool', models.IntegerField(null=True, db_column='HusbandBool', blank=True)),
                ('kemlerbool', models.IntegerField(null=True, db_column='KemlerBool', blank=True)),
                ('kaplanbool', models.IntegerField(null=True, db_column='KaplanBool', blank=True)),
                ('interests', models.CharField(max_length=255, blank=True)),
                ('education', models.CharField(max_length=250, blank=True)),
                ('work', models.CharField(max_length=255, blank=True)),
                ('notes1', models.CharField(max_length=255, blank=True)),
                ('notes2', models.CharField(max_length=255, blank=True)),
                ('notes3', models.CharField(max_length=255, blank=True)),
                ('birthdate', models.CharField(max_length=15, blank=True)),
                ('birthplace', models.CharField(max_length=100, blank=True)),
                ('deathdate', models.CharField(max_length=15, blank=True)),
                ('gender', models.CharField(max_length=1, db_column='Gender', blank=True)),
                ('origin', models.CharField(max_length=85, blank=True)),
                ('firstfamily', models.IntegerField(null=True, db_column='firstFamily', blank=True)),
                ('currentlocation', models.CharField(max_length=50, db_column='currentLocation', blank=True)),
                ('adoptedbool', models.IntegerField(null=True, db_column='adoptedBool', blank=True)),
                ('directbool', models.IntegerField(null=True, db_column='directBool', blank=True)),
                ('hidebool', models.IntegerField(null=True, db_column='hideBool', blank=True)),
                ('lastmodified', models.DateTimeField(null=True, db_column='lastModified', blank=True)),
                ('flag1', models.CharField(max_length=255, blank=True)),
                ('flag2', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Specialinfo',
            fields=[
                ('specialid', models.IntegerField(serialize=False, primary_key=True, db_column='specialID')),
                ('description', models.CharField(max_length=255, blank=True)),
                ('img', models.CharField(max_length=50, blank=True)),
                ('text', models.CharField(max_length=255, blank=True)),
                ('page', models.CharField(max_length=50, blank=True)),
                ('source', models.CharField(max_length=50, blank=True)),
            ],
            options={
                'db_table': 'specialinfo',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Specialinfoperson',
            fields=[
                ('specialgroupid', models.IntegerField(serialize=False, primary_key=True, db_column='specialgroupID')),
                ('infoid', models.IntegerField(null=True, db_column='infoID', blank=True)),
                ('type', models.IntegerField(null=True, blank=True)),
                ('subjectid', models.IntegerField(null=True, db_column='subjectID', blank=True)),
            ],
            options={
                'db_table': 'specialinfoPerson',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('changeid', models.IntegerField(serialize=False, primary_key=True, db_column='changeID')),
                ('userid', models.IntegerField(null=True, db_column='userID', blank=True)),
                ('personid', models.IntegerField(null=True, db_column='personID', blank=True)),
                ('familyid', models.IntegerField(null=True, db_column='familyID', blank=True)),
                ('date', models.DateTimeField(null=True, db_column='Date', blank=True)),
                ('moderated', models.IntegerField(null=True, db_column='Moderated', blank=True)),
                ('status', models.CharField(max_length=50, db_column='Status', blank=True)),
                ('notes', models.CharField(max_length=200, blank=True)),
            ],
            options={
                'db_table': 'updates',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.IntegerField(serialize=False, primary_key=True, db_column='userID')),
                ('email', models.CharField(max_length=50, blank=True)),
                ('sharedaccount', models.IntegerField(null=True, db_column='sharedAccount', blank=True)),
                ('password', models.CharField(max_length=50)),
                ('lastlogin', models.DateTimeField(null=True, db_column='lastLogin', blank=True)),
                ('personid', models.IntegerField(null=True, db_column='personID', blank=True)),
                ('createdate', models.DateTimeField(null=True, db_column='createDate', blank=True)),
                ('lastpestered', models.DateTimeField(null=True, db_column='lastPestered', blank=True)),
                ('keemaccess', models.IntegerField(null=True, db_column='KeemAccess', blank=True)),
                ('husbandaccess', models.IntegerField(null=True, db_column='HusbandAccess', blank=True)),
                ('kemleraccess', models.IntegerField(null=True, db_column='KemlerAccess', blank=True)),
                ('kaplanaccess', models.IntegerField(null=True, db_column='KaplanAccess', blank=True)),
                ('logins', models.IntegerField(null=True, db_column='Logins', blank=True)),
                ('activebool', models.IntegerField(null=True, db_column='ActiveBool', blank=True)),
                ('connection_notes', models.CharField(max_length=255, blank=True)),
                ('superadmin', models.IntegerField(null=True, db_column='superAdmin', blank=True)),
                ('furthesthtml', models.CharField(max_length=255, db_column='furthestHTML', blank=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
            bases=(models.Model,),
        ),
    ]
